- name: Init "Swarm Mode" on the first manager.
  shell: docker swarm init
        --listen-addr {{ swarn_manager_address }}:{{ swarn_manager_port }}
        --advertise-addr {{ swarn_manager_address }}
  when: "docker_info.stdout.find('Swarm: active') == -1"

- name: Get the worker join-token.
  shell: docker swarm join-token -q worker
  changed_when: False
  register: docker_worker_token

