- name: Wait for docker in manager to start
  wait_for:
    host: "{{ swarn_manager_address }}"
    port: "{{ swarn_manager_port }}"
    timeout: 120

- name: Join the pending Swarm worker nodes.
  shell: docker swarm join --token "{{ hostvars[groups['docker_swarm_manager'][0]]['docker_worker_token']['stdout'] }}" {{ swarn_manager_address }}:{{ swarn_manager_port }}
  changed_when: False
  when: "docker_info.stdout.find('Swarm: active') == -1 and docker_info.stdout.find('Swarm: pending') == -1"

